export default {
    BACKGROUND_PRIMARY: '#FAFAFA',
    BACKGROUND_SECONDARY: '#424242',
    BORDER_PRIMARY: '#EEEEEE',
    TEXT_PRIMARY: '#424242',
    TEXT_SECONDARY: '#FAFAFA',
    COLOR_PRIMARY: '#1E88E5',
    HOVER_PRIMARY: '#42A5F5'
}